/* The model: dimensions, stakeholders, moves, precedents.
   Facts cited in `basis` and `lesson` are from the public record. The scores
   (ideal points, weights, effects) are structured judgments and are editable
   in the app under Library → Assumptions. */
(function (root) {
  'use strict';
  var B = { R: 'Blueprint: Strategy to Reclaim the North (2025)', L: 'Blueprint: Cyprus–U.S. Strategic Leverage (2025)', U: 'Blueprint: Unified Cyprus (2025)', H: 'Blueprint: Holistic Strategy to Prevent Aggression (2025)', V: 'Proposal: A Vision for Peace and Prosperity (2024)', D: 'Proposal: Bridging Divides (2024)' };

  var M = {
    version: '1.0.0',
    tau: 0.35,
    costScale: 0.25,
    mirrors: ['https://samuelakosaonyejekwe.github.io/resolvethecyprusproblem/'],
    docs: [
      'Bridging Divides: A Vision for a Unified Cyprus (October 2024)',
      'Reunification of Cyprus: A Vision for Peace and Prosperity (October 2024)',
      'Strategic Rebirth of Cyprus: A Comprehensive Game-Theoretic Blueprint to Regain Sovereignty (June 2025)',
      'A Holistic Global Strategy to Prevent Military Aggression Against Cyprus (June 2025)',
      'Unified Cyprus Blueprint: Incentivised Reunification Without Two-State or Guarantor Framework (June 2025)',
      'Cyprus–U.S. Strategic Leverage Blueprint: A Non-Military Roadmap (August 2025)'
    ],
    cats: { deal: 'Settlement design', diplomatic: 'Diplomacy', legal: 'Law', economic: 'Economy', energy: 'Energy', security: 'Security', societal: 'Society' },
    outcomes: {
      reunified: { name: 'Verified reunification', icon: '◎', color: '#1f7a5a', desc: 'One state, foreign troops largely gone, arrangements holding.' },
      convergence: { name: 'Convergence', icon: '⇄', color: '#2f8f9d', desc: 'The sides are moving toward an agreed settlement and trust is building.' },
      stalemate: { name: 'Managed stalemate', icon: '≡', color: '#8a7a4d', desc: 'The division persists without crisis; time quietly entrenches it.' },
      confrontation: { name: 'Confrontation', icon: '⚡', color: '#c2702a', desc: 'High pressure and fraying calm: gains are possible, so is miscalculation.' },
      partition: { name: 'Partition entrenched', icon: '╫', color: '#7b5ea7', desc: 'Two separate entities in practice; reunification recedes out of reach.' },
      crisis: { name: 'Armed crisis', icon: '✸', color: '#b23a3a', desc: 'Military incidents or blockade; everything else is on hold.' }
    },

    dims: [
      { id: 'settle', name: 'Settlement track', short: 'Settlement', lens: 'Political', lo: 'Two separate states', hi: 'One reunified state', base: 46, drift: -0.5,
        desc: 'Where the political process is heading.',
        basis: 'UN-led talks have been stalled since Crans-Montana (July 2017). Informal UN meetings resumed in 2025, and Turkish Cypriots elected the pro-federation Tufan Erhürman in October 2025, while Ankara still voices a two-state position.' },
      { id: 'troops', name: 'Demilitarisation', short: 'Troops', lens: 'Security', lo: 'Reinforced garrison', hi: 'Verified full withdrawal', base: 12, drift: 0,
        desc: 'Foreign military presence on the island outside the British bases.',
        basis: 'Türkiye keeps an estimated 30,000–40,000 troops in the north. The 1960 Treaty of Guarantee remains formally in force. UNFICYP (about 800 troops) has patrolled the buffer zone since 1964.' },
      { id: 'econ', name: 'Island economic integration', short: 'Economy', lens: 'Economic', lo: 'Sealed economies', hi: 'Single island market', base: 24, drift: 0,
        desc: 'How far the two economies work as one.',
        basis: 'Green Line trade (EU Regulation 866/2004) is worth only about €15–16 million a year. The north uses the Turkish lira and depends on budget support from Ankara. Nine crossing points operate.' },
      { id: 'energy', name: 'East-Med energy', short: 'Energy', lens: 'Energy', lo: 'Contested by force', hi: 'Shared and monetised', base: 36, drift: 0,
        desc: 'Whether offshore gas and interconnection are developing cooperatively.',
        basis: 'Discoveries include Aphrodite, Calypso, Glaucus and Cronos; none is yet in production. Export via Egypt is under negotiation. Türkiye disputes parts of the Republic\'s EEZ and obstructed drilling in 2018–2020. The Great Sea Interconnector faces delays.' },
      { id: 'pressure', name: 'Cost of the status quo for Ankara', short: 'Pressure', lens: 'Legal', lo: 'None', hi: 'Severe', base: 24, drift: -0.8,
        desc: 'Legal, economic and diplomatic costs Türkiye bears for the present situation.',
        basis: 'UN Security Council Resolutions 541 and 550 keep the north unrecognised. The €90 million awarded in Cyprus v. Turkey (2014) is unpaid. EU accession talks are frozen; the 2019 EU sanctions framework over drilling has listed two people.' },
      { id: 'trust', name: 'Trust between the communities', short: 'Trust', lens: 'Social', lo: 'Hostile', hi: 'Confident', base: 36, drift: -0.4,
        desc: 'Readiness of Greek and Turkish Cypriots to share a state.',
        basis: 'In the 2004 referendums 65% of Turkish Cypriots voted yes and 76% of Greek Cypriots no. Bicommunal work continues: the Committee on Missing Persons has identified more than 1,000 of 2,002 missing.' },
      { id: 'stability', name: 'Stability', short: 'Stability', lens: 'Security', lo: 'Armed crisis', hi: 'Calm', base: 62, drift: 0.4,
        desc: 'Absence of military incidents and brinkmanship.',
        basis: 'No inter-state fighting since 1974, but recurrent friction: the 2020 naval stand-off, buffer-zone incidents such as Pyla in August 2023, and airspace violations.' },
      { id: 'trwest', name: 'Türkiye–West anchor', short: 'Türkiye–West', lens: 'Political', lo: 'Estranged', hi: 'Integrated', base: 42, drift: 0,
        desc: 'Depth of Türkiye\'s ties with the EU and the United States.',
        basis: 'EU–Türkiye customs union dates from 1995 and its modernisation is blocked. Türkiye was removed from the F-35 programme in 2019 and sanctioned under CAATSA in 2020; F-16 sales were approved in January 2024.' },
      { id: 'tcstatus', name: 'Turkish Cypriot standing', short: 'TC standing', lens: 'Political', lo: 'Isolated, dependent', hi: 'Equal, connected', base: 30, drift: -0.3,
        desc: 'Political equality, welfare and access to the world for Turkish Cypriots.',
        basis: 'The EU acquis is suspended in the north (Protocol 10). There are no direct flights except via Türkiye, and no direct trade regulation. Turkish Cypriots can hold Republic of Cyprus (EU) passports.' },
      { id: 'rocstand', name: 'Republic\'s standing and deterrence', short: 'RoC standing', lens: 'Security', lo: 'Isolated, exposed', hi: 'Anchored, protected', base: 58, drift: 0,
        desc: 'Alliances, legal position and ability to deter coercion.',
        basis: 'EU member since 2004 and in the eurozone since 2008; held the EU Council presidency in the first half of 2026. The US lifted its arms restrictions in 2022. Not a NATO member; the National Guard is small.' }
    ],

    players: [
      { id: 'ROC', name: 'Republic of Cyprus', short: 'ROC', color: '#b5652b', power: 45, inertia: 0.3, veto: true,
        role: 'The internationally recognised government, led by the Greek Cypriot community. EU member with a veto in the Council.',
        ideal: { settle: 95, troops: 100, econ: 80, energy: 88, pressure: 65, trust: 80, stability: 85, trwest: 55, tcstatus: 70, rocstand: 95 },
        w: { settle: 22, troops: 20, econ: 5, energy: 9, pressure: 7, trust: 6, stability: 10, trwest: 1, tcstatus: 4, rocstand: 16 },
        interests: ['End of the occupation and return of territory and property', 'A single sovereignty, citizenship and international personality', 'Freedom to develop offshore energy', 'Security without foreign guarantor rights'],
        redlines: ['No two-state outcome or recognition of a second state', 'No permanent Turkish troops or unilateral right of intervention'],
        leverage: ['EU membership: unanimity gives a say over every EU–Türkiye upgrade', 'International law and UN resolutions on its side', 'Offshore gas and a location that partners need', 'Ability to open EU benefits to Turkish Cypriots'],
        vuln: ['Small armed forces and no alliance guarantee', 'Greek Cypriot voters rejected the 2004 plan; any deal must pass a referendum', 'EU partners tire of vetoes that cost them business with Ankara', 'Energy projects are exposed to naval harassment'] },
      { id: 'TC', name: 'Turkish Cypriots', short: 'TC', color: '#2f8f9d', power: 20, inertia: 0.5, veto: true,
        role: 'The Turkish Cypriot community and its leadership in the north. Any settlement needs their separate consent.',
        ideal: { settle: 72, troops: 55, econ: 90, energy: 80, pressure: 30, trust: 80, stability: 90, trwest: 75, tcstatus: 100, rocstand: 50 },
        w: { settle: 10, troops: 8, econ: 15, energy: 6, pressure: 4, trust: 7, stability: 12, trwest: 5, tcstatus: 30, rocstand: 3 },
        interests: ['Political equality and effective participation in government', 'An end to isolation: trade, travel, sport, universities', 'Security against a return to the 1963–74 violence', 'Preserving a distinct identity, also in relation to Ankara'],
        redlines: ['Not to be reduced to a minority under majority rule', 'No settlement that leaves them without credible security'],
        leverage: ['A separate referendum: their yes is required', 'They are the swing player both sides need', 'Many hold EU citizenship through the Republic'],
        vuln: ['Economic and budget dependence on Türkiye and the lira', 'Demographic change from settlement', 'Leadership has limited room when Ankara disagrees'] },
      { id: 'TR', name: 'Türkiye', short: 'TR', color: '#b23a3a', power: 85, inertia: 0.6, veto: true,
        role: 'Guarantor power with troops in the north; the only state that recognises the "TRNC". NATO member and EU candidate.',
        ideal: { settle: 25, troops: 15, econ: 55, energy: 45, pressure: 0, trust: 50, stability: 70, trwest: 85, tcstatus: 85, rocstand: 25 },
        w: { settle: 15, troops: 20, econ: 4, energy: 10, pressure: 12, trust: 2, stability: 4, trwest: 13, tcstatus: 8, rocstand: 8 },
        interests: ['Strategic depth and a military foothold south of Anatolia', 'A share of East-Med energy and maritime zones', 'Security and status of Turkish Cypriots', 'Economic access to Europe on its own terms'],
        redlines: ['No outcome presented as defeat or forced withdrawal', 'No exclusion from Eastern Mediterranean energy'],
        leverage: ['Overwhelming local military superiority', 'NATO membership and a veto on NATO–EU cooperation', 'Control of migration flows toward the EU', 'Financial lifeline of the north'],
        vuln: ['Lira weakness and reliance on Western capital and markets', 'Defence industry depends on Western components', 'Cost of subsidising the north', 'Reputation and legal liability as occupying power'] },
      { id: 'GR', name: 'Greece', short: 'GR', color: '#22648f', power: 40, inertia: 0.8,
        role: 'Guarantor power, EU and NATO member, closest ally of the Republic of Cyprus.',
        ideal: { settle: 90, troops: 95, econ: 70, energy: 85, pressure: 45, trust: 75, stability: 92, trwest: 60, tcstatus: 60, rocstand: 85 },
        w: { settle: 15, troops: 12, econ: 2, energy: 14, pressure: 4, trust: 3, stability: 25, trwest: 8, tcstatus: 2, rocstand: 15 },
        interests: ['Calm in the Aegean and Eastern Mediterranean', 'A settlement in line with UN resolutions', 'Energy interconnection with Cyprus and Israel'],
        redlines: ['No legitimisation of faits accomplis by force'],
        leverage: ['EU and NATO voice', 'Air and naval capability', 'Guarantor status it is willing to give up'],
        vuln: ['Its own disputes with Türkiye over the Aegean', 'Cost of the interconnector'] },
      { id: 'EU', name: 'European Union', short: 'EU', color: '#3a4fa0', power: 70, inertia: 1.0,
        role: 'The Union of which Cyprus is a member and Türkiye a candidate; holds the main economic incentives.',
        ideal: { settle: 90, troops: 85, econ: 85, energy: 85, pressure: 35, trust: 80, stability: 92, trwest: 75, tcstatus: 70, rocstand: 75 },
        w: { settle: 14, troops: 6, econ: 8, energy: 12, pressure: 4, trust: 5, stability: 22, trwest: 16, tcstatus: 5, rocstand: 8 },
        interests: ['Stability on its south-eastern border', 'A working relationship with Ankara on trade, migration and defence', 'Energy diversification', 'Ending the anomaly of EU law suspended on EU territory'],
        redlines: ['No settlement incompatible with EU law and values'],
        leverage: ['Customs-union modernisation, visa liberalisation, access to defence funds', 'Financial aid for Turkish Cypriots', 'Sanctions, by unanimity'],
        vuln: ['Unanimity: 27 capitals with different interests in Türkiye', 'Dependence on Ankara over migration'] },
      { id: 'US', name: 'United States', short: 'US', color: '#4a5a6a', power: 90, inertia: 1.2,
        role: 'The power with most influence over Ankara\'s security and financial environment.',
        ideal: { settle: 80, troops: 70, econ: 60, energy: 85, pressure: 30, trust: 60, stability: 90, trwest: 90, tcstatus: 60, rocstand: 75 },
        w: { settle: 9, troops: 4, econ: 1, energy: 14, pressure: 5, trust: 1, stability: 22, trwest: 30, tcstatus: 1, rocstand: 13 },
        interests: ['Keeping Türkiye inside the Western alliance', 'Regional stability and energy corridors', 'Reliable access and partners in the Eastern Mediterranean'],
        redlines: ['No rupture inside NATO', 'No armed escalation between partners'],
        leverage: ['Arms sales and export controls', 'Sanctions and the dollar system', 'Convening power'],
        vuln: ['Needs Ankara on Russia, the Black Sea and the Middle East', 'Policy changes with administrations'] },
      { id: 'UK', name: 'United Kingdom', short: 'UK', color: '#6b4c8a', power: 45, inertia: 1.2,
        role: 'Guarantor power, permanent Security Council member, holder of two Sovereign Base Areas on the island.',
        ideal: { settle: 78, troops: 60, econ: 65, energy: 70, pressure: 30, trust: 70, stability: 92, trwest: 80, tcstatus: 65, rocstand: 62 },
        w: { settle: 15, troops: 4, econ: 5, energy: 6, pressure: 4, trust: 8, stability: 30, trwest: 20, tcstatus: 3, rocstand: 5 },
        interests: ['Unimpeded use of the bases at Akrotiri and Dhekelia', 'Good relations with both Nicosia and Ankara', 'A settlement that does not reopen the base question'],
        redlines: ['Status of the Sovereign Base Areas'],
        leverage: ['Pen-holder on Cyprus at the Security Council', 'Guarantor status', 'Offered in past talks to cede about half the base territory'],
        vuln: ['Seen as partial by both sides', 'Large Cypriot diaspora of both communities at home'] },
      { id: 'UN', name: 'United Nations', short: 'UN', color: '#3f8fd0', power: 25, inertia: 0.5,
        role: 'The Secretary-General\'s good offices and the peacekeeping force. Convenes the talks; cannot impose.',
        ideal: { settle: 85, troops: 80, econ: 80, energy: 70, pressure: 30, trust: 90, stability: 95, trwest: 60, tcstatus: 75, rocstand: 60 },
        w: { settle: 22, troops: 8, econ: 8, energy: 0, pressure: 6, trust: 20, stability: 28, trwest: 0, tcstatus: 8, rocstand: 0 },
        interests: ['A negotiated settlement within Security Council parameters', 'Calm in the buffer zone', 'A credible exit for a mission deployed since 1964'],
        redlines: ['No endorsement of secession'],
        leverage: ['Legitimacy and convening role', 'Reports that name responsibility'],
        vuln: ['Depends on the consent of the parties and the permanent five'] },
      { id: 'RU', name: 'Russia', short: 'RU', color: '#7a6a5a', power: 50, inertia: 0.6,
        role: 'Permanent Security Council member with interests in keeping the West divided and its gas market share.',
        ideal: { settle: 45, troops: 30, econ: 50, energy: 30, pressure: 50, trust: 40, stability: 55, trwest: 15, tcstatus: 50, rocstand: 42 },
        w: { settle: 12, troops: 8, econ: 0, energy: 25, pressure: 0, trust: 0, stability: 8, trwest: 35, tcstatus: 0, rocstand: 12 },
        interests: ['Distance between Ankara and the West', 'Fewer rival gas supplies to Europe', 'No expansion of NATO infrastructure'],
        redlines: ['A settlement that brings Cyprus into NATO'],
        leverage: ['Security Council veto', 'Energy and trade ties with Türkiye'],
        vuln: ['Diminished standing in Nicosia since 2022', 'Limited means to shape events on the island'] },
      { id: 'REG', name: 'Regional partners', short: 'REG', color: '#a8862b', power: 45, inertia: 0.8,
        role: 'Israel, Egypt and the Gulf states: energy partners of Cyprus, each with its own relationship with Ankara.',
        ideal: { settle: 70, troops: 70, econ: 60, energy: 92, pressure: 45, trust: 60, stability: 88, trwest: 55, tcstatus: 55, rocstand: 85 },
        w: { settle: 6, troops: 4, econ: 3, energy: 32, pressure: 4, trust: 0, stability: 25, trwest: 7, tcstatus: 0, rocstand: 19 },
        interests: ['Monetising Eastern Mediterranean gas', 'Secure sea lanes and cables', 'A predictable Türkiye'],
        redlines: ['Disruption of energy infrastructure'],
        leverage: ['Egyptian LNG plants as the export route', 'Gulf investment that Ankara needs', 'Israeli defence and technology ties'],
        vuln: ['Their own disputes and rapprochements with Ankara', 'Regional wars crowd out the Cyprus file'] }
    ],

    moves: [
      /* ---- Republic of Cyprus ---- */
      { id: 'roc.talks', p: 'ROC', cat: 'deal', name: 'Table a federal deal with phased withdrawal', src: B.R + ' · ' + B.D, cost: 3, ps: 0.8, prec: ['annan', 'crans'],
        desc: 'Propose in UN-led talks a federation with political equality, a share of gas revenue for Turkish Cypriots and a dated, monitored troop withdrawal. If refused, the refusal itself is on record.',
        fx: { settle: 8, trust: 4, pressure: 2, trwest: 2 }, fail: { trust: -2 } },
      { id: 'roc.blueprint', p: 'ROC', cat: 'deal', name: 'Table the Unified Blueprint: one state, entrenched self-rule, no guarantors', src: B.U, cost: 4, ps: 0.75, req: { trust: [40, 100] }, prec: ['annan', 'aland', 'tyrol'],
        desc: 'One sovereignty and citizenship with a constitutionally entrenched Turkish Cypriot self-governing territory, parity in key portfolios, a narrow court-policed veto, and every step gated on verification.',
        fx: { settle: 10, trust: 5, tcstatus: 4, pressure: 3 }, fail: { settle: -2, trust: -3 } },
      { id: 'roc.security', p: 'ROC', cat: 'deal', name: 'Propose a time-bound security compact to replace guarantees', src: B.U, cost: 2, ps: 0.7, prec: ['crans', 'camp', 'twoplusfour'],
        desc: 'A UN transition mission, an EU rule-of-law and border mission and independent monitoring, with a dated draw-down of foreign troops and automatic snap-back if a step is missed.',
        fx: { settle: 6, troops: 3, trust: 4, tcstatus: 2 }, fail: { trust: -2 } },
      { id: 'roc.escrow', p: 'ROC', cat: 'deal', name: 'Pre-fund a settlement fund released on verified milestones', src: B.U + ' · ' + B.L, cost: 4, ps: 0.8, prec: ['twoplusfour', 'minsk'],
        desc: 'Money for property compensation, infrastructure in the north and redeployment costs sits in escrow and is paid out only when independent verifiers certify each step. Cooperation pays now; defection costs at once.',
        fx: { trust: 5, settle: 4, tcstatus: 3, trwest: 2 } },
      { id: 'roc.property', p: 'ROC', cat: 'deal', name: 'Offer a property settlement menu', src: B.U, cost: 3, ps: 0.75, prec: ['loizidou', 'demopoulos'],
        desc: 'Restitution where feasible, exchange, long lease or compensation bonds, decided by an independent commission on a fixed clock.',
        fx: { trust: 5, settle: 4, pressure: -2 }, fail: { trust: -2 } },
      { id: 'roc.mediators', p: 'ROC', cat: 'diplomatic', name: 'Bring in neutral brokers on a fixed clock', src: B.R, cost: 1, ps: 0.6, prec: ['crans', 'lebanon'],
        desc: 'Ask a state trusted by both sides to broker UN-framework talks with a deadline to agree and a deadline to implement, and involve the United Kingdom as guarantor.',
        fx: { settle: 4, trust: 2, stability: 2 } },
      { id: 'roc.vetolift', p: 'ROC', cat: 'diplomatic', name: 'Offer to unblock a narrow EU–Türkiye trade basket for verified steps', src: B.U + ' · ' + B.V, cost: 3, ps: 0.8, prec: ['helsinki'],
        desc: 'Signal that Nicosia will not oppose a small, pre-defined and reversible package of customs and visa facilitation once agreed withdrawal steps are certified.',
        fx: { trwest: 6, pressure: -4, settle: 4, trust: 3 } },
      { id: 'roc.referendum', p: 'ROC', cat: 'deal', name: 'Put the agreed package to simultaneous referendums', src: B.U, cost: 4, ps: 0.6, after: ['tr.accept'], req: { settle: [70, 100], trust: [50, 100] }, prec: ['annan', 'gfa'],
        desc: 'Identical question in both communities on the same day, fixed threshold, international observers. The 2004 lesson: do not go to a vote before the public has seen the security and property terms working.',
        fx: { settle: 15, troops: 8, econ: 10, tcstatus: 8, rocstand: 6, trust: 6 }, fail: { settle: -12, trust: -10, rocstand: -4 },
        mods: [{ when: { trust: [65, 100] }, fx: { settle: 5, trust: 3 } }], mit: 'Build consent first: national dialogue, visible day-one benefits, and security terms the public can verify.' },
      { id: 'roc.consensus', p: 'ROC', cat: 'societal', name: 'National dialogue to build Greek Cypriot consensus', src: B.R, cost: 2, ps: 0.8, prec: ['annan'],
        desc: 'Bring parties, refugees\' associations and unions into shaping the offer, so that a deal is owned before it is voted on.',
        fx: { trust: 5, settle: 3, stability: 1 } },
      { id: 'roc.tcbenefits', p: 'ROC', cat: 'societal', name: 'Open EU benefits to Turkish Cypriots now', src: B.R + ' · ' + B.U, cost: 3, ps: 0.85, prec: ['crossings', 'greenline'],
        desc: 'Health-system access, recognition of qualifications, sports integration, pensions portability and EU programmes for Turkish Cypriots as citizens, without waiting for a settlement.',
        fx: { tcstatus: 9, trust: 7, econ: 4, settle: 3 } },
      { id: 'roc.crossings', p: 'ROC', cat: 'societal', name: 'Open new crossings and ease checkpoints', src: B.U, cost: 1, ps: 0.7, prec: ['crossings'],
        desc: 'More crossing points, longer hours, fast lanes for ambulances, school buses and commuters.',
        fx: { trust: 6, econ: 4, tcstatus: 2, stability: 2 } },
      { id: 'roc.greenline', p: 'ROC', cat: 'economic', name: 'Widen Green Line trade with "Cyprus origin" certification', src: B.U, cost: 2, ps: 0.8, prec: ['greenline'],
        desc: 'Let northern producers who meet EU standards certify and sell through the Republic\'s ports, with accredited labs and electronic seals.',
        fx: { econ: 8, tcstatus: 5, trust: 3 } },
      { id: 'roc.energyoffer', p: 'ROC', cat: 'energy', name: 'Offer a joint energy framework with escrowed revenue', src: B.R + ' · ' + B.U + ' · ' + B.D, cost: 4, ps: 0.75, prec: ['lebanon'],
        desc: 'One national hydrocarbons authority, a Turkish Cypriot revenue share held in escrow until settlement, and a technical panel to de-risk disputed blocks.',
        fx: { energy: 8, tcstatus: 5, trust: 4, settle: 3 }, fail: { trust: -2 } },
      { id: 'roc.gas', p: 'ROC', cat: 'energy', name: 'Fast-track gas exports with Egypt and the majors', src: B.R + ' · ' + B.L, cost: 2, ps: 0.7, prec: ['yavuz', 'lebanon'],
        desc: 'Bring Aphrodite and Cronos to Egyptian LNG plants with the operating companies, creating revenue and partners with a stake in calm seas.',
        fx: { energy: 9, econ: 3, rocstand: 5, stability: -2 }, fail: { energy: -2 } },
      { id: 'roc.energyweb', p: 'ROC', cat: 'energy', name: 'Energy Web: multiply energy ties across the region', src: B.H, cost: 2, ps: 0.75,
        desc: 'Spread interconnection, storage and supply agreements across Egypt, Israel, Jordan, the Gulf and the EU so that no single project can be isolated.',
        fx: { energy: 6, rocstand: 6 } },
      { id: 'roc.uspact', p: 'ROC', cat: 'security', name: 'Lock in the United States with a partnership stack', src: B.L, cost: 3, ps: 0.7, prec: ['itar'],
        desc: 'Defence cooperation, rotational access, energy and finance agreements, each reversible and audited, giving Washington tangible stakes in the Republic\'s security without permanent bases.',
        fx: { rocstand: 10, pressure: 4, stability: 2, trwest: -2 }, fail: { rocstand: 1 } },
      { id: 'roc.congress', p: 'ROC', cat: 'legal', name: 'Seek US legislation defining the north as occupied territory', src: B.L, cost: 2, ps: 0.35, prec: ['embargo75', 'caatsa'],
        desc: 'Work with Congress on findings, reporting duties and conditional measures tied to the occupation.',
        fx: { pressure: 9, rocstand: 2, trwest: -3 }, fail: { rocstand: -1 } },
      { id: 'roc.veto', p: 'ROC', cat: 'diplomatic', name: 'Hold the EU veto until there is progress', src: B.R, cost: 2, ps: 0.9, once: false, prec: ['helsinki'],
        desc: 'Block customs-union modernisation, visa liberalisation and access to EU defence funds for Türkiye unless there is movement on Cyprus.',
        fx: { pressure: 9, trwest: -6, rocstand: 1 } },
      { id: 'roc.sanctions', p: 'ROC', cat: 'diplomatic', name: 'Push for EU sanctions on occupation-linked entities', src: B.R, cost: 2, ps: 0.4, prec: ['eusanc19'],
        desc: 'Seek listings under the EU framework for those involved in unauthorised drilling, Varosha or settlement activity. Needs unanimity.',
        fx: { pressure: 8, trwest: -4, rocstand: 2 }, fail: { rocstand: -2 } },
      { id: 'roc.echr', p: 'ROC', cat: 'legal', name: 'Press execution of court judgments', src: B.R, cost: 1, ps: 0.8, once: false, prec: ['loizidou', 'cyvtr'],
        desc: 'Pursue property and human-rights cases and press the Council of Europe on the unpaid 2014 award.',
        fx: { pressure: 6, rocstand: 2, trust: -1 } },
      { id: 'roc.icj', p: 'ROC', cat: 'legal', name: 'Seek advance rulings on maritime rights', src: B.H, cost: 3, ps: 0.5, prec: ['lebanon'],
        desc: 'File for arbitration or an advisory opinion on interference with the Republic\'s maritime zones before any incident. Türkiye is not a party to the UN Convention on the Law of the Sea, which limits what can be compelled.',
        fx: { pressure: 6, energy: 3, rocstand: 4, stability: -2 }, fail: { rocstand: -3 } },
      { id: 'roc.defence', p: 'ROC', cat: 'security', name: 'Modernise defences and exercise with partners', src: B.R, cost: 4, ps: 0.85, prec: ['s300'],
        desc: 'Air defence, patrol vessels and surveillance, with joint exercises with Greece, France, Israel and Egypt. Deterrence without provocation is the aim; the 1998 missile crisis shows the risk.',
        fx: { rocstand: 8, stability: -4, pressure: 1 } },
      { id: 'roc.fortress', p: 'ROC', cat: 'security', name: 'Fortress Cyprus: harden infrastructure and civil defence', src: B.R, cost: 5, ps: 0.9,
        desc: 'Protected command and supply sites, shelters, surveillance grid, cyber defence, energy and water reserves: make coercion costly without threatening anyone.',
        fx: { rocstand: 6, stability: 2 } },
      { id: 'roc.cgsp', p: 'ROC', cat: 'security', name: 'Sovereignty partnership with willing EU states', src: B.H, cost: 3, ps: 0.5, prec: ['itar'],
        desc: 'Give the EU mutual-assistance clause (Article 42.7) practical content with a group of member states: planning, presence, agreed responses.',
        fx: { rocstand: 9, pressure: 3, stability: -1 }, fail: { rocstand: -2 } },
      { id: 'roc.trilateral', p: 'ROC', cat: 'security', name: 'Deepen the Israel–Greece–Cyprus compact', src: B.H, cost: 2, ps: 0.8,
        desc: 'Move the trilateral beyond energy into joint procurement, cyber, maritime security and industry.',
        fx: { rocstand: 7, energy: 3, stability: -2, pressure: 2 } },
      { id: 'roc.msc', p: 'ROC', cat: 'diplomatic', name: 'Found a Mediterranean Stability Council in Nicosia', src: B.H + ' · ' + B.L, cost: 2, ps: 0.6,
        desc: 'A standing regional forum on maritime safety, energy interconnection and conflict prevention, open to all coastal states that accept its rules.',
        fx: { rocstand: 5, stability: 3, energy: 2 }, fail: { rocstand: -1 } },
      { id: 'roc.india', p: 'ROC', cat: 'economic', name: 'Technology and corridor partnership with India', src: B.H, cost: 2, ps: 0.7,
        desc: 'Position Cyprus as a Mediterranean node of the India–Middle East–Europe corridor, with shipping, technology and defence-industry links.',
        fx: { rocstand: 5, econ: 3 } },
      { id: 'roc.diaspora', p: 'ROC', cat: 'societal', name: 'Activate the diaspora network', src: B.H, cost: 1, ps: 0.8,
        desc: 'Organise Cypriots abroad, especially in the US, UK and Australia, around policy, legal and media work.',
        fx: { pressure: 3, rocstand: 4 } },
      { id: 'roc.narrative', p: 'ROC', cat: 'diplomatic', name: 'Public diplomacy on the cost of division', src: B.R, cost: 1, ps: 0.8, once: false,
        desc: 'Document heritage loss, displacement and the missing, and set out the economic gain from reunification for both communities.',
        fx: { pressure: 4, rocstand: 3, trust: -1 } },
      { id: 'roc.gulf', p: 'ROC', cat: 'diplomatic', name: 'Open a quiet channel to Ankara through Gulf states', src: B.H, cost: 1, ps: 0.6,
        desc: 'Use partners trusted in Ankara to explore face-saving formulas away from publicity.',
        fx: { trust: 3, settle: 3, stability: 3, trwest: 1 } },
      { id: 'roc.buffer', p: 'ROC', cat: 'economic', name: 'Ports and airspace reciprocity ladder with Türkiye', src: B.H + ' · ' + B.U, cost: 3, ps: 0.5, req: { stability: [50, 100] }, prec: ['helsinki'],
        desc: 'Step-by-step mutual opening: Turkish ports and airspace to Cyprus-flag traffic against practical facilitation for Turkish carriers, starting with non-energy trade.',
        fx: { econ: 5, trwest: 4, stability: 4, trust: 3, pressure: -3 }, fail: { trust: -1 } },
      { id: 'roc.nato', p: 'ROC', cat: 'security', name: 'Seek a NATO partnership', src: B.H, cost: 2, ps: 0.2,
        desc: 'Apply for Partnership for Peace as a step toward closer ties. Requires consensus, so Türkiye can block it.',
        fx: { rocstand: 7, trwest: -2, stability: -2 }, fail: { rocstand: -1 } },
      { id: 'roc.bez', p: 'ROC', cat: 'economic', name: 'Create a bi-communal economic zone', src: B.D + ' · ' + B.V, cost: 3, ps: 0.7, prec: ['greenline', 'gfa'],
        desc: 'A shared zone straddling the line, backed by the EU, with one legal regime and incentives for investors, and its revenue split evenly between the two communities for services and infrastructure.',
        fx: { econ: 8, trust: 4, tcstatus: 4, settle: 2 }, fail: { trust: -1 } },
      { id: 'roc.neutral', p: 'ROC', cat: 'security', name: 'Offer permanent neutrality with international guarantees', src: B.D, cost: 3, ps: 0.65, prec: ['aland', 'crans'],
        desc: 'A reunified Cyprus would be a neutral state with no foreign troops, its security guaranteed by a multilateral treaty and monitored by international peacekeepers during a transition.',
        fx: { settle: 5, troops: 3, trust: 3, stability: 2, rocstand: -2 }, fail: { rocstand: -2 } },
      { id: 'roc.pact', p: 'ROC', cat: 'diplomatic', name: 'Propose a non-aggression pact tied to Türkiye\'s EU track', src: B.D + ' · ' + B.V, cost: 3, ps: 0.5, prec: ['helsinki'],
        desc: 'Cyprus and Türkiye renounce territorial claims and the use of force; in return Nicosia supports reopening Ankara\'s accession talks, conditional on reunification going ahead.',
        fx: { trwest: 5, settle: 4, stability: 4, pressure: -3 }, fail: { trust: -1 } },
      { id: 'roc.culture', p: 'ROC', cat: 'societal', name: 'Launch bicommunal education and culture exchanges', src: B.D + ' · ' + B.V, cost: 1, ps: 0.85, prec: ['cmp', 'gfa'],
        desc: 'Language learning in both directions, joint school projects, shared heritage work and exchanges, with EU support, so the next generation grows up knowing the other community.',
        fx: { trust: 6, settle: 2 } },
      { id: 'roc.hardline', p: 'ROC', cat: 'diplomatic', name: 'Suspend contacts until troops leave', cost: 1, ps: 0.95,
        desc: 'Refuse talks and confidence-building measures until withdrawal begins.',
        fx: { settle: -4, trust: -6, pressure: 2, tcstatus: -3 } },

      /* ---- Türkiye ---- */
      { id: 'tr.twostate', p: 'TR', cat: 'diplomatic', name: 'Press for two-state recognition', cost: 1, ps: 0.7, once: false, prec: ['udi', 'ots'],
        desc: 'Campaign for recognition of the "TRNC" and insist on sovereign equality as the basis for any talks.',
        fx: { settle: -8, tcstatus: 1, pressure: 5, trwest: -4, trust: -4 } },
      { id: 'tr.reinforce', p: 'TR', cat: 'security', name: 'Reinforce the garrison and bases in the north', cost: 2, ps: 0.9, req: { troops: [0, 60] },
        desc: 'Add drone, naval and air facilities and upgrade forces.',
        fx: { troops: -8, stability: -8, rocstand: -4, pressure: 6, trwest: -5 } },
      { id: 'tr.gunboat', p: 'TR', cat: 'energy', name: 'Naval pressure on drilling in the Republic\'s EEZ', cost: 2, ps: 0.75, once: false, req: { energy: [50, 100] }, prec: ['yavuz'],
        desc: 'Issue navigational warnings, shadow survey vessels and send drillships with escorts, as in 2018–2020.',
        fx: { energy: -12, stability: -8, pressure: 6, trwest: -5, rocstand: -5 } },
      { id: 'tr.varosha', p: 'TR', cat: 'diplomatic', name: 'Open more of Varosha under Turkish Cypriot administration', cost: 1, ps: 0.85, prec: ['varosha'],
        desc: 'Extend the 2020 reopening of the fenced-off town, contrary to Security Council Resolutions 550 and 789.',
        fx: { settle: -6, trust: -8, pressure: 7, tcstatus: 1 } },
      { id: 'tr.integrate', p: 'TR', cat: 'economic', name: 'Tie the north more closely to Türkiye', cost: 1, ps: 0.85,
        desc: 'Economic protocols, infrastructure and administrative alignment that deepen dependence on Ankara.',
        fx: { settle: -6, econ: -4, tcstatus: -3, rocstand: -2 } },
      { id: 'tr.retaliate', p: 'TR', cat: 'diplomatic', name: 'Retaliate against Nicosia\'s partners and projects', cost: 1, ps: 0.7, once: false,
        desc: 'Block NATO–EU cooperation, pressure companies and states working with the Republic, use migration as leverage.',
        fx: { rocstand: -6, trwest: -3, stability: -4 }, mods: [{ when: { pressure: [40, 100] }, fx: { pressure: -8 } }] },
      { id: 'tr.cbm', p: 'TR', cat: 'societal', name: 'Allow confidence-building measures', cost: 1, ps: 0.85, prec: ['crossings', 'cmp'],
        desc: 'Let new crossings, mobile-phone interoperability, electricity exchange and joint projects go ahead.',
        fx: { trust: 7, econ: 4, tcstatus: 3, stability: 4, trwest: 2, pressure: -2 } },
      { id: 'tr.talks', p: 'TR', cat: 'deal', name: 'Return to UN talks without preconditions', cost: 2, ps: 0.85, any: ['un.convene', 'us.mediate', 'roc.mediators', 'eu.envoy', 'uk.broker'], prec: ['crans'],
        desc: 'Drop the demand for prior recognition of sovereign equality and resume from where Crans-Montana ended.',
        fx: { settle: 7, trust: 5, trwest: 4, pressure: -4, stability: 3 },
        mods: [{ when: { pressure: [40, 100] }, fx: { pressure: -6, trwest: 3 } }, { when: { trust: [50, 100] }, fx: { tcstatus: 4 } }] },
      { id: 'tr.partial', p: 'TR', cat: 'security', name: 'Token troop reduction as a signal', cost: 2, ps: 0.9,
        desc: 'Withdraw a visible contingent to test what the other side offers in return.',
        fx: { troops: 8, trwest: 3, pressure: -4, stability: 3, trust: 4 },
        mods: [{ when: { pressure: [45, 100] }, fx: { pressure: -8, trwest: 4 } }] },
      { id: 'tr.energydeal', p: 'TR', cat: 'energy', name: 'Join an inclusive East-Med energy framework', cost: 2, ps: 0.7, any: ['roc.energyoffer', 'reg.inclusive'], prec: ['lebanon'],
        desc: 'Accept a technical arrangement on disputed waters and take part in regional energy cooperation.',
        fx: { energy: 14, trwest: 8, econ: 5, tcstatus: 4, stability: 6, pressure: -4 }, fail: { energy: -3 } },
      { id: 'tr.accept', p: 'TR', cat: 'deal', name: 'Sign a gated withdrawal-for-value roadmap', cost: 3, ps: 0.75, any: ['eu.package', 'roc.vetolift', 'us.offramp', 'roc.pact'], req: { trust: [45, 100] }, prec: ['twoplusfour', 'camp', 'baltic'],
        desc: 'Agree a dated, verified draw-down in exchange for escrowed economic and political rewards, presented at home as redeployment by choice.',
        fx: { troops: 14, settle: 14, trwest: 8, pressure: -8, econ: 5, tcstatus: 6, stability: 5, trust: 6 }, fail: { trust: -8, settle: -5 },
        mods: [{ when: { pressure: [38, 100] }, fx: { pressure: -12, trwest: 3 } }, { used: 'eu.package', fx: { trwest: 9, econ: 3 } }, { used: 'roc.vetolift', fx: { trwest: 5 } }, { used: 'us.offramp', fx: { trwest: 7, econ: 3 } },
          { used: 'roc.escrow', fx: { econ: 4, tcstatus: 4 } }, { used: 'roc.security', fx: { tcstatus: 5, stability: 3 } }, { used: 'roc.energyoffer', fx: { trwest: 2, tcstatus: 3 } }, { used: 'roc.pact', fx: { trwest: 4, stability: 2 } }, { used: 'roc.neutral', fx: { tcstatus: 3, stability: 2 } }] },
      { id: 'tr.withdraw', p: 'TR', cat: 'security', name: 'Complete the verified withdrawal', cost: 2, ps: 0.8, after: ['tr.accept', 'roc.referendum'], prec: ['twoplusfour', 'baltic', 'camp'],
        desc: 'Carry out the roadmap: units leave on schedule, sites are handed over, verifiers certify, rewards are released.',
        fx: { troops: 48, trwest: 30, pressure: -30, stability: 8, tcstatus: 10, econ: 10, rocstand: 4 }, fail: { trust: -10, stability: -6, pressure: 10 },
        commit: [{ v: 2 }, { used: 'roc.escrow', v: 2.5 }, { used: 'roc.security', v: 2 }, { used: 'un.security', v: 1.5 }, { used: 'eu.package', v: 1 }],
        commitNote: 'Bound by the signed roadmap. Each commitment device in place raises the price of reneging: escrowed funds, the security compact with snap-back, the UN-mandated transition, and EU tranches.' },

      /* ---- Turkish Cypriots ---- */
      { id: 'tc.federal', p: 'TC', cat: 'deal', name: 'Table a federal proposal with political equality', cost: 2, ps: 0.8, prec: ['annan', 'crans'],
        desc: 'Put forward a bizonal, bicommunal federation with effective participation and a timetable.',
        fx: { settle: 8, trust: 6, tcstatus: 3, trwest: 2 } },
      { id: 'tc.cbm', p: 'TC', cat: 'societal', name: 'Open crossings and joint services', cost: 1, ps: 0.8, prec: ['crossings'],
        desc: 'New crossing points and practical cooperation on health, environment and emergencies.',
        fx: { trust: 8, econ: 5, tcstatus: 3, stability: 3 } },
      { id: 'tc.greenline', p: 'TC', cat: 'economic', name: 'Align with EU standards and scale Green Line trade', cost: 2, ps: 0.75, prec: ['greenline'],
        desc: 'Adopt EU product rules and certification so that goods and services can reach the EU market.',
        fx: { econ: 9, tcstatus: 5, trust: 3 } },
      { id: 'tc.civic', p: 'TC', cat: 'societal', name: 'Back the bicommunal civic platform', cost: 1, ps: 0.85, prec: ['cmp'],
        desc: 'Unions, teachers, business chambers and youth groups working across the divide.',
        fx: { trust: 7, settle: 3, stability: 2 } },
      { id: 'tc.property', p: 'TC', cat: 'legal', name: 'Speed up the Immovable Property Commission', cost: 2, ps: 0.7, prec: ['demopoulos'],
        desc: 'Faster decisions and real restitution for Greek Cypriot owners.',
        fx: { trust: 6, pressure: -3, tcstatus: 2, settle: 2 } },
      { id: 'tc.recognition', p: 'TC', cat: 'diplomatic', name: 'Seek recognition and direct flights through friendly states', cost: 2, ps: 0.4, prec: ['ots', 'udi'],
        desc: 'Lobby the Organization of Turkic States and others for upgraded status and direct links.',
        fx: { settle: -8, tcstatus: 3, trust: -6, pressure: 3, rocstand: -3 }, fail: { tcstatus: -3, trust: -3 } },
      { id: 'tc.align', p: 'TC', cat: 'diplomatic', name: 'Align fully with Ankara\'s line', cost: 0, ps: 0.95,
        desc: 'Adopt the two-state position and accept closer integration with Türkiye.',
        fx: { settle: -5, tcstatus: -4, trust: -4, troops: -2 } },
      { id: 'tc.referendum', p: 'TC', cat: 'deal', name: 'Campaign for yes in the Turkish Cypriot referendum', cost: 2, ps: 0.7, after: ['tr.accept'], req: { settle: [65, 100] }, prec: ['annan'],
        desc: 'Lead the yes campaign for the agreed package.',
        fx: { settle: 8, tcstatus: 10, trust: 4, econ: 4 }, fail: { settle: -6, trust: -5 } },

      /* ---- Greece ---- */
      { id: 'gr.calm', p: 'GR', cat: 'diplomatic', name: 'Keep the Athens–Ankara dialogue alive', cost: 1, ps: 0.85, once: false, prec: ['helsinki'],
        desc: 'Continue the "calm waters" agenda begun with the 2023 Athens Declaration.',
        fx: { stability: 6, trwest: 4, trust: 2 } },
      { id: 'gr.defence', p: 'GR', cat: 'security', name: 'Joint defence planning and air cover for Cyprus', cost: 3, ps: 0.85, prec: ['s300'],
        desc: 'Revive joint defence planning and visible presence.',
        fx: { rocstand: 7, stability: -3, pressure: 2 } },
      { id: 'gr.interconnector', p: 'GR', cat: 'energy', name: 'Build the Great Sea Interconnector', cost: 4, ps: 0.55,
        desc: 'Finance and lay the Crete–Cyprus power cable despite cost disputes and Turkish objections.',
        fx: { energy: 8, rocstand: 4, econ: 3 }, fail: { energy: -3 } },
      { id: 'gr.linkage', p: 'GR', cat: 'diplomatic', name: 'Tie EU–Türkiye upgrades to Cyprus progress', cost: 2, ps: 0.8,
        desc: 'Insist with Nicosia that defence-fund access and customs-union upgrade depend on movement.',
        fx: { pressure: 8, trwest: -5, rocstand: 3 } },
      { id: 'gr.guarantee', p: 'GR', cat: 'deal', name: 'Offer to end guarantor rights and match troop reductions', cost: 1, ps: 0.9, prec: ['crans'],
        desc: 'Declare readiness to abolish the 1960 guarantees and withdraw the Greek contingent in step with Türkiye.',
        fx: { settle: 4, troops: 3, trust: 3 } },

      /* ---- European Union ---- */
      { id: 'eu.package', p: 'EU', cat: 'economic', name: 'Offer Ankara a conditional incentive package', cost: 3, ps: 0.75, prec: ['helsinki', 'twoplusfour'],
        desc: 'Customs-union modernisation, visa facilitation and defence-fund access, released in tranches against verified steps on Cyprus.',
        fx: { trwest: 6, pressure: 3, settle: 3 }, fail: { trwest: -1 },
        mods: [{ used: 'roc.vetolift', fx: { trwest: 5, settle: 3, stability: 2 } }, { used: 'roc.escrow', fx: { settle: 2, trust: 2 } }] },
      { id: 'eu.sanctions', p: 'EU', cat: 'legal', name: 'Adopt targeted sanctions', cost: 4, ps: 0.6, prec: ['eusanc19'],
        desc: 'List entities tied to unauthorised drilling, Varosha or settlement activity.',
        fx: { pressure: 14, trwest: -10, stability: -4, rocstand: 4 }, fail: { rocstand: -2 } },
      { id: 'eu.tcfund', p: 'EU', cat: 'economic', name: 'Scale up aid and direct engagement with Turkish Cypriots', cost: 1, ps: 0.85, prec: ['greenline'],
        desc: 'Expand the aid programme, scholarships, standards alignment and preparation for EU law.',
        fx: { tcstatus: 8, econ: 6, trust: 4, settle: 2 } },
      { id: 'eu.envoy', p: 'EU', cat: 'diplomatic', name: 'Put political weight behind the UN process', cost: 1, ps: 0.8,
        desc: 'An empowered EU envoy working alongside the UN, with the Union\'s instruments on the table.',
        fx: { settle: 5, trust: 3, rocstand: 2 } },
      { id: 'eu.unconditional', p: 'EU', cat: 'economic', name: 'Deepen ties with Ankara without Cyprus conditions', cost: 2, ps: 0.5,
        desc: 'Move ahead on trade, migration and defence cooperation, working around Nicosia\'s objections.',
        fx: { trwest: 12, pressure: -10, rocstand: -8, settle: -3 }, fail: { rocstand: -2 } },
      { id: 'eu.defence', p: 'EU', cat: 'security', name: 'Give the mutual-assistance clause practical content', cost: 3, ps: 0.55,
        desc: 'Planning, maritime presence and agreed responses for a member state under threat.',
        fx: { rocstand: 9, stability: 2, pressure: 4, trwest: -3 }, fail: { rocstand: -1 } },
      { id: 'eu.energy', p: 'EU', cat: 'energy', name: 'Finance East-Med energy links', cost: 2, ps: 0.8,
        desc: 'Grants and guarantees for interconnection, LNG and hydrogen that end the island\'s energy isolation.',
        fx: { energy: 9, econ: 3, rocstand: 3 } },

      /* ---- United States ---- */
      { id: 'us.pact', p: 'US', cat: 'security', name: 'Strategic partnership with Nicosia', cost: 2, ps: 0.8, prec: ['itar'],
        desc: 'Defence cooperation, security assistance and energy and finance links.',
        fx: { rocstand: 10, pressure: 4, trwest: -3, energy: 3 } },
      { id: 'us.condition', p: 'US', cat: 'security', name: 'Condition arms sales on Cyprus steps', cost: 4, ps: 0.6, prec: ['embargo75', 'f16', 'caatsa'],
        desc: 'Tie aircraft deliveries, upgrades and re-entry into programmes to verifiable moves.',
        fx: { pressure: 14, trwest: -6 }, fail: { pressure: 2, trwest: -3 },
        mods: [{ used: 'roc.uspact', fx: { rocstand: 5, energy: 3 } }, { used: 'us.offramp', fx: { settle: 4, trwest: 3 } }] },
      { id: 'us.sanctions', p: 'US', cat: 'legal', name: 'Targeted designations and export controls', src: B.L, cost: 4, ps: 0.8, prec: ['brunson', 'caatsa'],
        desc: 'Narrow, reversible measures on officials and firms that sustain the occupation, each paired with a way out.',
        fx: { pressure: 13, trwest: -9, stability: -3 } },
      { id: 'us.offramp', p: 'US', cat: 'deal', name: 'Sponsor a phased withdrawal protocol with escrowed rewards', src: B.L, cost: 3, ps: 0.65, prec: ['camp', 'twoplusfour'],
        desc: 'Put American weight behind a UN-registered timetable with a reconstruction fund and graduated relief.',
        fx: { settle: 5, trwest: 4, trust: 2, pressure: 2 }, fail: { settle: -1 },
        mods: [{ used: 'roc.uspact', fx: { rocstand: 3, stability: 3 } }, { used: 'roc.escrow', fx: { settle: 3, trwest: 2 } }] },
      { id: 'us.mediate', p: 'US', cat: 'diplomatic', name: 'High-level mediation linking Cyprus to regional deals', cost: 2, ps: 0.6, req: { settle: [52, 100] }, prec: ['camp', 'lebanon'],
        desc: 'An envoy with presidential backing who links Cyprus to energy and security arrangements Ankara wants.',
        fx: { settle: 7, trwest: 4, stability: 3, trust: 2 } },
      { id: 'us.transact', p: 'US', cat: 'security', name: 'Prioritise Ankara without Cyprus linkage', cost: 1, ps: 0.85, prec: ['f16'],
        desc: 'Arms sales and sanctions relief in exchange for cooperation elsewhere.',
        fx: { trwest: 12, pressure: -12, rocstand: -6 },
        mods: [{ used: 'roc.uspact', fx: { rocstand: -5, energy: -4, stability: -3 } }] },
      { id: 'us.energy', p: 'US', cat: 'energy', name: 'Back US companies and the energy corridor through Cyprus', src: B.L, cost: 1, ps: 0.85,
        desc: 'Diplomatic and financial support for American operators in the EEZ and for corridor infrastructure.',
        fx: { energy: 10, rocstand: 5, stability: 2, pressure: 2 } },

      /* ---- United Kingdom ---- */
      { id: 'uk.guarantor', p: 'UK', cat: 'deal', name: 'Declare readiness to end guarantor rights', cost: 1, ps: 0.9, prec: ['crans'],
        desc: 'State that London will give up its 1960 role within a settlement.',
        fx: { settle: 5, troops: 3, trust: 3 } },
      { id: 'uk.sba', p: 'UK', cat: 'deal', name: 'Offer base territory as part of a settlement', cost: 2, ps: 0.85, prec: ['annan'],
        desc: 'Renew the offer made in 2004 and after to cede around half of the base areas.',
        fx: { settle: 4, econ: 3, trust: 2, rocstand: 2 } },
      { id: 'uk.broker', p: 'UK', cat: 'diplomatic', name: 'Broker the security chapter', cost: 2, ps: 0.6,
        desc: 'Use pen-holder and guarantor roles to draft a security transition acceptable to both sides.',
        fx: { settle: 5, stability: 2, trwest: 2, trust: 2 } },
      { id: 'uk.ankara', p: 'UK', cat: 'security', name: 'Deepen defence trade with Ankara unconditionally', cost: 1, ps: 0.85,
        desc: 'Aircraft sales and industrial cooperation without reference to Cyprus.',
        fx: { trwest: 7, pressure: -6, rocstand: -4 } },

      /* ---- United Nations ---- */
      { id: 'un.convene', p: 'UN', cat: 'deal', name: 'Convene an enlarged meeting and appoint a full envoy', cost: 1, ps: 0.75, prec: ['crans'],
        desc: 'Bring the two sides and the three guarantors together and name a standing envoy.',
        fx: { settle: 6, trust: 4, stability: 2 } },
      { id: 'un.cbm', p: 'UN', cat: 'societal', name: 'Broker practical cooperation', cost: 1, ps: 0.8, once: false, prec: ['cmp', 'crossings'],
        desc: 'Crossings, demining, cemeteries, environment and youth committees.',
        fx: { trust: 7, econ: 2, stability: 3 } },
      { id: 'un.security', p: 'UN', cat: 'deal', name: 'Design a mandated security transition', cost: 2, ps: 0.7, req: { settle: [50, 100] }, prec: ['crans', 'camp'],
        desc: 'Verification, policing and a transition mission to replace the guarantee system.',
        fx: { settle: 5, troops: 3, trust: 3 } },
      { id: 'un.report', p: 'UN', cat: 'diplomatic', name: 'Name obstruction in the Secretary-General\'s report', cost: 2, ps: 0.8,
        desc: 'Attribute responsibility for lack of progress.',
        fx: { pressure: 6, trust: -2, rocstand: 2 } },

      /* ---- Russia ---- */
      { id: 'ru.shield', p: 'RU', cat: 'diplomatic', name: 'Shield the status quo at the Security Council', cost: 1, ps: 0.85,
        desc: 'Oppose deadlines, arbitration or any mission with a Western lead.',
        fx: { settle: -4, pressure: -5, trwest: -2 } },
      { id: 'ru.energy', p: 'RU', cat: 'energy', name: 'Deepen energy ties with Ankara', cost: 2, ps: 0.8,
        desc: 'Nuclear, gas-hub and payment arrangements that give Türkiye an alternative to the West.',
        fx: { trwest: -9, energy: -4, pressure: -4 } },
      { id: 'ru.north', p: 'RU', cat: 'diplomatic', name: 'Expand presence in the north', cost: 1, ps: 0.7,
        desc: 'Consular services and commercial links for Russian residents in the north.',
        fx: { settle: -5, tcstatus: 2, rocstand: -4, trwest: -2 } },
      { id: 'ru.support', p: 'RU', cat: 'diplomatic', name: 'Back UN parameters in return for Cypriot non-alignment', cost: 1, ps: 0.6,
        desc: 'Support a settlement that keeps the island outside NATO.',
        fx: { settle: 3, rocstand: -3, stability: 2 } },

      /* ---- Regional partners ---- */
      { id: 'reg.trilateral', p: 'REG', cat: 'security', name: 'Make the trilateral formats permanent', cost: 2, ps: 0.8,
        desc: 'Standing secretariats and security cooperation for the Cyprus–Greece–Israel and Cyprus–Greece–Egypt formats.',
        fx: { rocstand: 8, energy: 5, pressure: 3 } },
      { id: 'reg.gas', p: 'REG', cat: 'energy', name: 'Bring Cypriot gas to market through Egypt', cost: 2, ps: 0.7, prec: ['lebanon'],
        desc: 'Pipelines to Egyptian processing and LNG plants.',
        fx: { energy: 12, econ: 4, rocstand: 4 }, fail: { energy: -2 } },
      { id: 'reg.inclusive', p: 'REG', cat: 'energy', name: 'Invite Türkiye into the gas forum on conditions', cost: 2, ps: 0.5, prec: ['lebanon'],
        desc: 'A seat in regional energy cooperation in return for respect for existing maritime agreements.',
        fx: { energy: 8, trwest: 5, stability: 4, pressure: -3 }, fail: { energy: -2 } },
      { id: 'reg.mediate', p: 'REG', cat: 'diplomatic', name: 'Run a back-channel between Ankara and Nicosia', cost: 1, ps: 0.6,
        desc: 'Gulf or Egyptian good offices, out of public view.',
        fx: { trust: 3, settle: 4, stability: 3, trwest: 2 } },
      { id: 'reg.normalise', p: 'REG', cat: 'diplomatic', name: 'Put normalisation with Ankara first', cost: 1, ps: 0.7,
        desc: 'Repair bilateral relations with Türkiye and lower the priority of the Cyprus partnership.',
        fx: { trwest: 5, rocstand: -5, pressure: -5, energy: -3 } },
      { id: 'reg.corridor', p: 'REG', cat: 'economic', name: 'Anchor the corridor and data cables on Cyprus', cost: 2, ps: 0.7,
        desc: 'Route India–Middle East–Europe infrastructure through the island.',
        fx: { econ: 5, rocstand: 6, energy: 4 } }
    ],

    precedents: [
      { id: 'annan', scope: 'cy', name: 'Annan Plan referendums', year: '2004', outcome: 'failure', wiki: 'Annan Plan', cats: ['deal'],
        lesson: 'A comprehensive UN plan was approved by 65% of Turkish Cypriots and rejected by 76% of Greek Cypriots a week before EU accession. Security, property and the absence of any cost of voting no decided it: a deal has to be owned by both publics before the vote.' },
      { id: 'crans', scope: 'cy', name: 'Crans-Montana conference', year: '2017', outcome: 'failure', wiki: '2015–2017 Cyprus talks', cats: ['deal', 'security'],
        lesson: 'The closest the sides have come. It collapsed over guarantees and troops: Türkiye would not accept zero troops and no right of intervention from day one. Security is the chapter that must be solved, not postponed.' },
      { id: 'crossings', scope: 'cy', name: 'Opening of the crossing points', year: '2003', outcome: 'success', wiki: 'United Nations Buffer Zone in Cyprus', cats: ['societal'],
        lesson: 'After 29 years the line opened and millions of crossings followed without serious incident. Contact is safe and popular; on its own it did not produce a settlement.' },
      { id: 'greenline', scope: 'cy', name: 'Green Line Regulation', year: '2004', outcome: 'mixed', wiki: 'Green Line (Cyprus)', cats: ['economic'],
        lesson: 'Legal trade across the line exists but stays small because of standards, logistics and political reluctance on both sides. Economic bridges need active administration, not just permission.' },
      { id: 'cmp', scope: 'cy', name: 'Committee on Missing Persons', year: '1981–', outcome: 'success', wiki: 'Civilian casualties and displacements during the Cyprus conflict', cats: ['societal'],
        lesson: 'A bicommunal body under UN chairmanship has identified more than 1,000 missing people from both communities. Humanitarian cooperation insulated from politics can work for decades.' },
      { id: 'loizidou', scope: 'cy', name: 'Loizidou v. Turkey', year: '1996', outcome: 'success', wiki: 'Loizidou v. Turkey', cats: ['legal'],
        lesson: 'The European Court of Human Rights held Türkiye responsible for denying a Greek Cypriot owner access to her property; Ankara paid in 2003. Litigation fixes responsibility and has a price, but it did not return the property.' },
      { id: 'cyvtr', scope: 'cy', name: 'Cyprus v. Turkey, just satisfaction', year: '2014', outcome: 'mixed', wiki: 'Cyprus v. Turkey', cats: ['legal'],
        lesson: 'The Court awarded €90 million for the missing and the enclaved. It remains unpaid: judgments raise cost and reputation damage, but enforcement against a determined state is weak.' },
      { id: 'demopoulos', scope: 'cy', name: 'Demopoulos v. Turkey', year: '2010', outcome: 'mixed', wiki: 'Judiciary of Northern Cyprus', cats: ['legal'],
        lesson: 'The Court accepted the Immovable Property Commission in the north as a domestic remedy. Legal strategy can produce results the claimant did not intend.' },
      { id: 'udi', scope: 'cy', name: 'Unilateral declaration of independence', year: '1983', outcome: 'failure', wiki: 'Northern Cyprus', cats: ['diplomatic'],
        lesson: 'Security Council Resolution 541 declared it legally invalid; four decades on, only Türkiye recognises it. Unilateral status changes have not gained acceptance.' },
      { id: 'ots', scope: 'cy', name: 'Observer status at the Organization of Turkic States', year: '2022', outcome: 'mixed', wiki: 'Organization of Turkic States', cats: ['diplomatic'],
        lesson: 'Symbolic gains are available, but in 2025 Central Asian members reaffirmed the UN resolutions in a joint declaration with the EU. Recognition campaigns meet a ceiling.' },
      { id: 'varosha', scope: 'cy', name: 'Partial reopening of Varosha', year: '2020', outcome: 'failure', wiki: 'Varosha, Famagusta', cats: ['diplomatic'],
        lesson: 'Opening the beachfront drew Security Council condemnation and hardened Greek Cypriot opinion without improving Turkish Cypriot standing.' },
      { id: 'yavuz', scope: 'cy', name: 'Drillship stand-off in the EEZ', year: '2018–2020', outcome: 'mixed', wiki: 'Cyprus–Turkey maritime zones dispute', cats: ['energy'],
        lesson: 'Turkish warships blocked a drillship in 2018 and Turkish vessels drilled in waters claimed by Cyprus. EU sanctions were minimal; the pressure eased only when Ankara chose to de-escalate with the EU in 2021.' },
      { id: 'eusanc19', scope: 'cy', name: 'EU sanctions framework on drilling', year: '2019', outcome: 'mixed', wiki: 'Cyprus–Turkey maritime zones dispute', cats: ['legal', 'diplomatic'],
        lesson: 'The framework exists but only two individuals have been listed. Unanimity makes EU sanctions on Türkiye hard to obtain and easy to dilute.' },
      { id: 's300', scope: 'cy', name: 'S-300 missile crisis', year: '1997–1998', outcome: 'failure', wiki: 'Cypriot S-300 crisis', cats: ['security'],
        lesson: 'Cyprus ordered Russian air-defence missiles; Türkiye threatened to strike them; they ended up on Crete. Arms purchases that the stronger side reads as a change in the balance can provoke rather than deter.' },
      { id: 'itar', scope: 'cy', name: 'Lifting of US arms restrictions on Cyprus', year: '2020–2022', outcome: 'success', wiki: 'Cyprus–United States relations', cats: ['security'],
        lesson: 'Patient alignment — port access rules, financial reforms, legislation in Congress — ended a 1987 embargo. Standing with Washington can be built step by step.' },
      { id: 'embargo75', scope: 'cy', name: 'US arms embargo on Turkey', year: '1975–1978', outcome: 'failure', wiki: 'Turkey–United States relations', cats: ['security', 'legal'],
        lesson: 'Congress cut arms sales after the invasion. Türkiye closed US bases and did not withdraw; the embargo was lifted in three years. Blunt pressure without an exit ramp entrenched positions.' },
      { id: 'helsinki', scope: 'cy', name: 'Helsinki summit and earthquake diplomacy', year: '1999', outcome: 'success', wiki: 'Greek–Turkish earthquake diplomacy', cats: ['diplomatic', 'economic'],
        lesson: 'A credible EU membership perspective and Greek–Turkish rapprochement produced the most flexible Turkish position on Cyprus in decades (2002–2004). Incentives move Ankara when they are believed.' },
      { id: 'f16', scope: 'else', name: 'F-16 sale and Sweden\'s NATO accession', year: '2024', outcome: 'success', wiki: 'Accession of Sweden to NATO', cats: ['security'],
        lesson: 'Ankara ratified Swedish membership and Washington approved the F-16 sale days later. Transactional linkage with Türkiye works when both sides can claim a win.' },
      { id: 'brunson', scope: 'else', name: 'Sanctions over the Brunson detention', year: '2018', outcome: 'success', wiki: 'Andrew Brunson', cats: ['legal'],
        lesson: 'US sanctions on two ministers and tariff measures were followed by a sharp fall in the lira; the pastor was released within months and the sanctions lifted. Narrow, reversible measures with a clear ask produced a result.' },
      { id: 'caatsa', scope: 'else', name: 'CAATSA sanctions over the S-400 purchase', year: '2020', outcome: 'mixed', wiki: 'Countering America\'s Adversaries Through Sanctions Act', cats: ['legal', 'security'],
        lesson: 'Sanctions on Türkiye\'s defence procurement agency and removal from the F-35 programme imposed real cost, yet the S-400s stayed. Pressure does not reverse a decision tied to sovereignty and prestige unless an acceptable way out is offered.' },
      { id: 'twoplusfour', scope: 'else', name: 'German reunification and Soviet withdrawal', year: '1990–1994', outcome: 'success', wiki: 'Treaty on the Final Settlement with Respect to Germany', cats: ['deal', 'security'],
        lesson: 'About 340,000 Soviet troops left eastern Germany on a four-year schedule; Germany paid billions of marks for housing and transition. Withdrawal for value, on a timetable, with dignity, is how a large army was persuaded to go home.' },
      { id: 'baltic', scope: 'else', name: 'Russian troop withdrawal from the Baltic states', year: '1994', outcome: 'success', wiki: 'Baltic states under Soviet rule (1944–1991)', cats: ['security'],
        lesson: 'Decades of Western non-recognition preserved the legal position; withdrawal came when the larger power wanted Western cooperation and received housing aid and face-saving terms.' },
      { id: 'camp', scope: 'else', name: 'Camp David and the Sinai withdrawal', year: '1978–1982', outcome: 'success', wiki: 'Camp David Accords', cats: ['deal', 'security'],
        lesson: 'Israel withdrew from Sinai in phases, each matched by Egyptian steps, with US guarantees and aid and a multinational observer force that still operates. Phasing, verification and a great-power sponsor made withdrawal acceptable.' },
      { id: 'gfa', scope: 'else', name: 'Good Friday Agreement', year: '1998', outcome: 'success', wiki: 'Good Friday Agreement', cats: ['deal', 'societal'],
        lesson: 'Power-sharing, cross-community consent and simultaneous referendums north and south ended a thirty-year conflict. Both publics voted yes because both governments and an outside sponsor campaigned for it.' },
      { id: 'aland', scope: 'else', name: 'Åland Islands autonomy', year: '1921', outcome: 'success', wiki: 'Åland Islands dispute', cats: ['deal'],
        lesson: 'Sovereignty stayed with Finland while language, culture and self-government were internationally guaranteed and the islands demilitarised. Entrenched autonomy inside one state has lasted a century.' },
      { id: 'tyrol', scope: 'else', name: 'South Tyrol autonomy package', year: '1972–1992', outcome: 'success', wiki: 'South Tyrol', cats: ['deal'],
        lesson: 'Italy implemented a detailed autonomy package measure by measure; Austria declared the dispute closed only when the last was done. Benchmark-by-benchmark implementation built trust that words had not.' },
      { id: 'lebanon', scope: 'else', name: 'Israel–Lebanon maritime boundary agreement', year: '2022', outcome: 'success', wiki: 'Israeli–Lebanese maritime border dispute', cats: ['energy'],
        lesson: 'Two states technically at war settled a gas dispute through US mediation and a revenue arrangement, without recognising each other. Energy deals can be reached without settling the political conflict first.' },
      { id: 'minsk', scope: 'else', name: 'Minsk agreements', year: '2014–2015', outcome: 'failure', wiki: 'Minsk agreements', cats: ['deal'],
        lesson: 'Sequencing was ambiguous, verification weak and no cost followed non-compliance. Agreements without automatic consequences decay.' },
      { id: 'dayton', scope: 'else', name: 'Dayton Agreement', year: '1995', outcome: 'mixed', wiki: 'Dayton Agreement', cats: ['deal'],
        lesson: 'The war ended, but ethnic vetoes at every level produced a state that struggles to decide anything. Power-sharing needs deadlock-breaking rules.' }
    ]
  };

  /* Subjects: what each move is about in the world's news. Each subject has a
     search phrase used to pull current coverage, statements and meetings. */
  M.topics = {
    talks: { name: 'Settlement talks', q: '(cyprus OR cypriot) (talks OR negotiations OR settlement OR reunification OR federation)' },
    security: { name: 'Guarantees and security arrangements', q: '(cyprus OR cypriot) (guarantees OR guarantor OR "troop withdrawal" OR peacekeeping OR UNFICYP OR neutrality)' },
    troops: { name: 'Turkish forces on the island', q: '(cyprus OR cypriot) ("turkish troops" OR "turkish army" OR "turkish military" OR "military base" OR occupation)' },
    property: { name: 'Property and refugees', q: '(cyprus OR cypriot) (property OR refugees OR restitution OR compensation OR "missing persons")' },
    cbm: { name: 'Crossings and confidence-building', q: '(cyprus OR cypriot) ("crossing point" OR crossings OR "confidence-building" OR "buffer zone" OR bicommunal)' },
    trade: { name: 'Trade and Turkish Cypriot economy', q: '("turkish cypriot" OR "northern cyprus" OR "green line") (trade OR economy OR investment OR aid OR flights)' },
    gas: { name: 'Offshore gas', q: 'cyprus (gas OR drilling OR Aphrodite OR Cronos OR ExxonMobil OR Chevron OR "exclusive economic zone")' },
    grid: { name: 'Energy links and interconnector', q: 'cyprus (interconnector OR "electricity cable" OR "Great Sea" OR hydrogen OR "energy corridor")' },
    euturkey: { name: 'EU–Türkiye relations', q: '(turkey OR turkiye) ("customs union" OR "visa liberalisation" OR "accession talks" OR "european union") cyprus' },
    sanctions: { name: 'Sanctions on Türkiye', q: '(turkey OR turkiye) (sanctions OR "restrictive measures" OR designations) (cyprus OR drilling OR CAATSA)' },
    uscyprus: { name: 'United States–Cyprus partnership', q: 'cyprus ("united states" OR washington OR pentagon OR congress) (defense OR defence OR partnership OR "visa waiver" OR arms)' },
    usturkey: { name: 'United States–Türkiye dealings', q: '(turkey OR turkiye) ("F-35" OR "F-16" OR CAATSA OR "S-400") ("united states" OR washington OR congress)' },
    courts: { name: 'Courts and legal action', q: '(cyprus OR cypriot) ("court of human rights" OR ECHR OR "council of europe" OR ruling OR lawsuit OR arbitration)' },
    maritime: { name: 'Maritime zones and naval incidents', q: 'cyprus (maritime OR warship OR NAVTEX OR "law of the sea" OR "naval exercise") (turkey OR turkiye OR turkish)' },
    varosha: { name: 'Varosha', q: '(Varosha OR Maras) (cyprus OR cypriot OR famagusta)' },
    recognition: { name: 'Two-state push and recognition', q: '("two-state" OR "TRNC" OR "northern cyprus") (recognition OR sovereignty OR "turkic states" OR "direct flights")' },
    defence: { name: 'Defence of the Republic', q: 'cyprus ("national guard" OR "air defence" OR "air defense" OR "military exercise" OR NATO OR missile OR "mutual assistance" OR Frontex)' },
    regional: { name: 'Regional partnerships', q: 'cyprus (israel OR egypt OR emirates OR saudi OR india OR trilateral OR IMEC) (cooperation OR summit OR corridor OR agreement)' },
    greeceturkey: { name: 'Greece–Türkiye dialogue', q: 'greece (turkey OR turkiye) (dialogue OR "calm waters" OR aegean OR Mitsotakis) (Erdogan OR talks OR meeting)' },
    britain: { name: 'United Kingdom and the bases', q: 'cyprus (britain OR british) (bases OR Akrotiri OR Dhekelia OR guarantor OR Eurofighter)' },
    un: { name: 'United Nations process', q: 'cyprus (Guterres OR "security council" OR "united nations" OR Holguin) (envoy OR report OR meeting OR resolution)' },
    russia: { name: 'Russia\'s role', q: '(russia OR russian) (cyprus OR "northern cyprus" OR Akkuyu OR turkey) (consulate OR gas OR nuclear OR veto OR "security council")' },
    society: { name: 'Public opinion and civil society', q: '(cyprus OR cypriot) (referendum OR poll OR "public opinion" OR diaspora OR "civil society" OR education OR heritage)' }
  };
  /* A report counts only if its headline is plainly about the subject. */
  var CY = 'cypr|nicosia|varosha|famagusta|unficyp|erh[uü]rman|christodoulides', TK = 'turk|türk|ankara|erdo[gğ]an';
  Object.keys(M.topics).forEach(function (t) { M.topics[t].must = CY; });
  M.topics.euturkey.must = TK; M.topics.sanctions.must = TK; M.topics.usturkey.must = TK;
  M.topics.greeceturkey.must = 'gree|athens|mitsotakis|aegean'; M.topics.russia.must = 'russia|putin|kremlin|moscow|akkuyu';
  M.topics.maritime.must = CY + '|' + TK;
  var SUB = {
    talks: 'talks|negotiat|settlement|solution|reunif|federa|peace|envoy|two-state', security: 'guarant|troop|peacekeep|unficyp|neutral|security|withdraw',
    troops: 'troop|army|military|base|occup|soldier', property: 'refugee|restitut|compensat|missing persons|the missing|displaced|immovable|property (claim|commission|right|issue|dispute)|usurp',
    cbm: 'crossing|confidence|buffer|bi-?communal|checkpoint', trade: 'trade|econom|invest|\\baid\\b|flight|halloumi|green line|export',
    gas: 'gas|drill|aphrodite|cronos|exxon|chevron|eez|hydrocarbon', grid: 'interconnector|cable|electric|hydrogen|grid|power link',
    euturkey: 'customs|visa|accession|\\beu\\b|european|brussels|membership', sanctions: 'sanction|restrictive|caatsa|designat|embargo',
    uscyprus: '\\bu\\.?s\\.?\\b|united states|washington|american|pentagon|congress|visa waiver', usturkey: 'f-?35|f-?16|caatsa|s-?400|washington|\\bu\\.?s\\.?\\b|congress',
    courts: 'court|echr|ruling|lawsuit|arbitrat|judg|legal|council of europe', maritime: 'maritime|warship|navtex|naval|navy|vessel|\\bsea\\b',
    varosha: 'varosha|mara[sş]', recognition: 'two-state|trnc|recogni|sovereign|turkic|direct flight',
    defence: 'defen[cs]e|guard|military|exercise|nato|missile|frontex|\\barms\\b|army', regional: 'israel|egypt|emirates|\\buae\\b|saudi|india|trilateral|imec|gulf|jordan|leban',
    greeceturkey: 'turk|türk|erdo[gğ]an|ankara', britain: 'brit|\\buk\\b|bases|akrotiri|dhekelia|\\braf\\b|london',
    un: '\\bun\\b|united nations|guterres|security council|envoy|holgu', russia: 'cypr|turk|türk|akkuyu|ankara',
    society: 'referendum|poll|opinion|diaspora|civil society|education|heritage|youth|school'
  };
  Object.keys(SUB).forEach(function (t) { M.topics[t].sub = SUB[t]; });

  var TOPIC = {
    talks: ['roc.talks', 'roc.blueprint', 'roc.mediators', 'roc.gulf', 'roc.hardline', 'tr.talks', 'tr.accept', 'tc.federal', 'us.offramp', 'us.mediate', 'reg.mediate', 'eu.envoy'],
    security: ['roc.security', 'roc.neutral', 'gr.guarantee', 'uk.guarantor', 'uk.broker', 'un.security', 'tr.withdraw'],
    troops: ['tr.reinforce', 'tr.partial'],
    property: ['roc.property', 'roc.escrow', 'tc.property'],
    cbm: ['roc.crossings', 'tr.cbm', 'tc.cbm', 'un.cbm', 'tc.civic'],
    trade: ['roc.tcbenefits', 'roc.greenline', 'roc.bez', 'tc.greenline', 'eu.tcfund', 'tr.integrate', 'roc.buffer'],
    gas: ['roc.gas', 'roc.energyoffer', 'us.energy', 'reg.gas', 'reg.inclusive', 'tr.energydeal'],
    grid: ['roc.energyweb', 'gr.interconnector', 'eu.energy'],
    euturkey: ['roc.vetolift', 'roc.veto', 'roc.pact', 'eu.package', 'eu.unconditional', 'gr.linkage'],
    sanctions: ['roc.sanctions', 'eu.sanctions', 'us.sanctions'],
    uscyprus: ['roc.uspact', 'roc.congress', 'us.pact'],
    usturkey: ['us.condition', 'us.transact'],
    courts: ['roc.echr', 'roc.icj'],
    maritime: ['tr.gunboat', 'tr.retaliate'],
    varosha: ['tr.varosha'],
    recognition: ['tr.twostate', 'tc.recognition', 'tc.align', 'ru.north'],
    defence: ['roc.defence', 'roc.fortress', 'roc.cgsp', 'roc.nato', 'gr.defence', 'eu.defence'],
    regional: ['roc.trilateral', 'roc.msc', 'roc.india', 'reg.trilateral', 'reg.normalise', 'reg.corridor'],
    greeceturkey: ['gr.calm'],
    britain: ['uk.sba', 'uk.ankara'],
    un: ['un.convene', 'un.report', 'ru.shield', 'ru.support'],
    russia: ['ru.energy'],
    society: ['roc.consensus', 'roc.referendum', 'roc.diaspora', 'roc.narrative', 'roc.culture', 'tc.referendum']
  };
  Object.keys(TOPIC).forEach(function (t) { TOPIC[t].forEach(function (id) { M.moves.forEach(function (m) { if (m.id === id) m.topic = t; }); }); });

  root.MODEL = M;
  if (typeof module !== 'undefined' && module.exports) module.exports = M;
})(typeof self !== 'undefined' ? self : this);
